"""Stage 6 — admin CRUD codegen, page-level parallel.

Step 3.6 Part A wires the entire flow but defaults to ``mock=True`` so
no Anthropic credits are spent. Part B (when credits arrive) sets
``mock=False`` and lets Claude generate real list / create / edit
pages.

Per-page pipeline
-----------------
For each (entity, page_type) pair:
  1. Build a prompt via the prompt modules.
  2. If mock=True: write a placeholder JSX that imports AuthGuard and
     the page-specific db_admin helper.
  3. If mock=False: call `call_claude_for_json` once, receive a file,
     and write it to disk.
  4. Run the static validator on the emitted file; surface any issues
     in the result dict.

Parallelism
-----------
The pipeline builds a flat list of ALL (entity, page_type) tuples
across the data model and gathers them under a single
``asyncio.Semaphore`` — the same shape ``website_orchestrator`` uses
for parallel page generation. ``generate_entity_crud`` still exists as
a per-entity convenience (it gathers its own 3 pages internally), but
the pipeline uses ``generate_one_admin_page`` directly for full N×3
concurrency.
"""
from __future__ import annotations

import asyncio
import logging
from typing import Any

from app.services.project_writer import write_text_file
from app.services.admin_codegen_validator import (
    summarise_issues,
    validate_generated_crud_file,
)
from app.services.data_model import DataModel, TableDefinition
from app.services.prompts import (
    build_create_view_prompt,
    build_edit_view_prompt,
    build_list_view_prompt,
)

logger = logging.getLogger(__name__)


# ── Tunables ─────────────────────────────────────────────────────────

# Rough per-page cost — claude-sonnet-4-6 at ~$3/Mtok in + $15/Mtok out.
# A 4K-input / 3K-output page lands around ~$0.05. We log this BEFORE
# the call so a pipeline operator can see the budget the run will spend.
_EST_PAGE_COST_USD = 0.05

# Default model — picked to match the website page_codegen path.
_DEFAULT_MODEL = "claude-sonnet-4-6"


# ── Mock page generator ──────────────────────────────────────────────

def _mock_page_jsx(
    entity: TableDefinition,
    page_type: str,
    plan: dict,
) -> str:
    """A self-explanatory placeholder JSX file.

    The mock honours the SAME contract Claude will: 'use client',
    AuthGuard import, React Router import, plus the page-specific
    db_admin helper. Validates the import contract without burning
    credits.
    """
    label_plural   = entity.plural_label or entity.name
    label_singular = entity.singular_label or entity.name
    field_count    = len(entity.fields)
    component_name = "".join(p.title() for p in entity.name.split("_"))
    slug = entity.name.replace("_", "-")

    # Per-page identifiers + imports — matches what the validator
    # expects for `page_type`.
    config = {
        "list": (
            "ListPage",
            'import { Link } from "react-router-dom";\n',
            'import { listCollection, deleteRow } from "@/lib/db_admin.js";\n',
            "  void listCollection;\n  void deleteRow;\n",
            f'  const route = "/{slug}/new";\n  void route;\n',
        ),
        "create": (
            "CreatePage",
            'import { useNavigate } from "react-router-dom";\n',
            'import { createRow } from "@/lib/db_admin.js";\n',
            "  const navigate = useNavigate();\n  void createRow;\n  void navigate;\n",
            "",
        ),
        "edit": (
            "EditPage",
            'import { useNavigate, useParams } from "react-router-dom";\n',
            'import { listCollection, updateRow, deleteRow } from "@/lib/db_admin.js";\n',
            "  const navigate = useNavigate();\n  const { id } = useParams();\n  void listCollection;\n  void updateRow;\n  void deleteRow;\n  void navigate;\n  void id;\n",
            "",
        ),
    }[page_type]
    suffix, router_import, helper_import, setup_lines, extra_lines = config

    brand = (plan.get("branding") or {}).get("brand_name") or "Admin"

    return (
        '"use client";\n'
        '/* MOCK page generated by Step 3.6 Part A.\n'
        ' * Real CRUD UI will be generated by Claude in Part B.\n'
        ' * Imports AuthGuard + db_admin so the contract Claude will\n'
        ' * inherit is exercised even in mock mode.\n'
        ' */\n'
        f'{router_import}'
        'import { AuthGuard } from "@/components/AuthGuard.jsx";\n'
        f'{helper_import}'
        '\n'
        f'export default function {component_name}{suffix}() {{\n'
        f'{setup_lines}'
        f'{extra_lines}'
        '  return (\n'
        '    <AuthGuard>\n'
        '      <div className="p-8 max-w-2xl">\n'
        '        {typeof Link === "function" ? null : null}\n'
        f'        <h1 className="text-3xl font-bold mb-2">{label_plural}</h1>\n'
        f'        <p className="text-sm text-muted-foreground mb-6">{brand} admin</p>\n'
        '        <p className="text-muted-foreground mb-2">\n'
        f'          This is a MOCK page for the <code>{entity.name}</code> entity.\n'
        '        </p>\n'
        '        <p className="text-sm text-muted-foreground">\n'
        f'          Page type: <strong>{page_type}</strong>. ' \
        f'Entity: <code>{entity.name}</code> ({field_count} field' \
        f'{"" if field_count == 1 else "s"}).<br />\n'
        '          When Anthropic credits are available and\n'
        '          <code> ADMIN_CODEGEN_MOCK=false</code>, Claude will\n'
        f'          generate the real {page_type} UI for {label_singular} here.\n'
        '        </p>\n'
        '      </div>\n'
        '    </AuthGuard>\n'
        '  );\n'
        '}\n'
    )


# ── Real-Claude path ─────────────────────────────────────────────────

async def _call_claude_for_one_page(
    *,
    prompt: dict[str, str],
    anthropic_key: str,
    label: str,
) -> tuple[str | None, float]:
    """One Claude call → (file_content, actual_cost_usd).

    Returns ``(None, 0.0)`` on any failure so the caller can decide
    whether to fall back to the mock page or surface the issue.
    """
    # Lazy import — keeps mock-mode test imports cheap and avoids a
    # circular import via project_generator.
    from app.services.project_generator import call_claude_for_json

    try:
        result = await call_claude_for_json(
            system_prompt=prompt["system"],
            user_prompt=prompt["user"],
            api_key=anthropic_key,
            websocket=None,
            model=_DEFAULT_MODEL,
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning("admin_codegen %s: Claude call threw — %s", label, exc)
        return None, 0.0

    if not result or not result.get("files"):
        logger.warning("admin_codegen %s: empty result from Claude", label)
        return None, 0.0

    # Spec: exactly one file. If Claude returned more, use the first
    # whose path looks like the page route — anything else is content
    # Claude added uninvited (rare but possible).
    files = result["files"]
    first = files[0]
    raw_content = first.get("content")
    if not isinstance(raw_content, str) or not raw_content.strip():
        logger.warning(
            "admin_codegen %s: file came back with non-string content (%s)",
            label, type(raw_content).__name__,
        )
        return None, 0.0

    # Actual cost is unknown without parsing usage from the Anthropic
    # response — call_claude_for_json doesn't surface it today. For
    # Part B we'd thread it through; for Part A we report the estimate.
    return raw_content, _EST_PAGE_COST_USD


# ── Main entry ───────────────────────────────────────────────────────

def pages_for_entity(
    entity: TableDefinition,
    admin_plan: dict,
) -> list[tuple[str, str, dict]]:
    """Return the (page_type, rel_path, prompt) triples for one entity.

    Public helper so the pipeline can build a flat task list across
    entities for parallel Stage-6 codegen.
    """
    base = "".join(part.title() for part in entity.name.split("_"))
    return [
        ("list",   f"src/pages/{base}List.jsx",        build_list_view_prompt(entity, admin_plan)),
        ("create", f"src/pages/{base}Create.jsx",      build_create_view_prompt(entity, admin_plan)),
        ("edit",   f"src/pages/{base}Edit.jsx",        build_edit_view_prompt(entity, admin_plan)),
    ]


async def generate_one_admin_page(
    *,
    entity: TableDefinition,
    page_type: str,
    rel_path: str,
    prompt: dict[str, str],
    admin_plan: dict,
    workspace_path: str,
    anthropic_key: str,
    mock: bool,
) -> dict[str, Any]:
    """Generate ONE admin CRUD page.

    Returns a flat dict per page so the pipeline can gather many
    concurrently and aggregate them afterwards:

      ``entity``     — table.name (for grouping in the caller)
      ``page_type``  — "list" | "create" | "edit"
      ``rel_path``   — relative path written (or attempted)
      ``written``    — True if a file was written
      ``page_cost``  — actual $ spent on this page (0 when mock=True)
      ``issues``     — list of validator issue strings (empty == clean)
    """
    label = f"{entity.name}/{page_type}"

    if mock:
        content: str | None = _mock_page_jsx(entity, page_type, admin_plan)
        page_cost = 0.0
    else:
        content, page_cost = await _call_claude_for_one_page(
            prompt=prompt,
            anthropic_key=anthropic_key,
            label=label,
        )

    if content is None:
        return {
            "entity":     entity.name,
            "page_type":  page_type,
            "rel_path":   rel_path,
            "written":    False,
            "page_cost":  page_cost,
            "issues":     ["claude returned no usable file"],
        }

    # Validate before writing — same check whether mock or real.
    issues = validate_generated_crud_file(
        content,
        expected_entity=entity.name,
        page_type=page_type,
    )
    if issues:
        logger.warning(
            "admin_codegen %s: validator flagged:\n%s",
            label, summarise_issues(issues),
        )

    safe_rel_path = write_text_file(workspace_path, rel_path, content)
    if not safe_rel_path:
        return {
            "entity":     entity.name,
            "page_type":  page_type,
            "rel_path":   rel_path,
            "written":    False,
            "page_cost":  page_cost,
            "issues":     issues + ["unsafe or rejected output path"],
        }

    return {
        "entity":     entity.name,
        "page_type":  page_type,
        "rel_path":   safe_rel_path,
        "written":    True,
        "page_cost":  page_cost,
        "issues":     issues,
    }


async def generate_entity_crud(
    *,
    entity: TableDefinition,
    data_model: DataModel,
    admin_plan: dict,
    workspace_path: str,
    anthropic_key: str = "",
    mock: bool = True,
) -> dict[str, Any]:
    """Generate the 3 CRUD pages for one entity, in parallel.

    Kept as a public entry-point because tests + ad-hoc callers use it,
    but the pipeline now builds a flatter task list across ALL entities
    via `pages_for_entity` + `generate_one_admin_page` so all N×3 pages
    can fire under one bounded semaphore.

    Returns a dict with:
      • ``files_written``         — list of relative paths
      • ``claude_cost_estimate``  — sum of per-page budget estimates
      • ``claude_actual_cost``    — actual spend (0 when mock=True)
      • ``validation_errors``     — list of `{file, issues}` dicts for
                                    any file that failed the static
                                    validator
    """
    _ = data_model  # reserved for future cross-entity context

    pages = pages_for_entity(entity, admin_plan)

    # 3 pages per entity — independent prompts, no shared state, safe
    # to gather in parallel.
    results = await asyncio.gather(*[
        generate_one_admin_page(
            entity=entity, page_type=page_type, rel_path=rel_path,
            prompt=prompt, admin_plan=admin_plan,
            workspace_path=workspace_path, anthropic_key=anthropic_key,
            mock=mock,
        )
        for page_type, rel_path, prompt in pages
    ])

    files_written:     list[str] = [r["rel_path"] for r in results if r["written"]]
    validation_errors: list[dict[str, Any]] = [
        {"file": r["rel_path"], "issues": r["issues"]}
        for r in results if r["issues"]
    ]
    cost_actual   = sum(r["page_cost"] for r in results)
    cost_estimate = len(pages) * _EST_PAGE_COST_USD

    logger.info(
        "admin_codegen %s: %d files written (mock=%s, validator_errors=%d)",
        entity.name, len(files_written), mock, len(validation_errors),
    )

    return {
        "files_written":        files_written,
        "claude_cost_estimate": round(cost_estimate, 4),
        "claude_actual_cost":   round(cost_actual,   4),
        "validation_errors":    validation_errors,
    }
