"""Deterministic src/config/navigation.js builder for react-admin / vue-admin.

The template ships a `navigation.js` with a specific contract:

    export const navigation = [{key, label, icon: 'LucideName', path}, ...]
    export const modules    = [{key, label, icon}]
    export const appConfig  = {name, logo}

Sidebar.jsx, Header.jsx, LoginPage.jsx, etc. all import these named
exports. Phase 1/2 LLM frequently rewrites navigation.js in its own
shape — grouped items, lucide-imports as identifiers, and (most
commonly) drops the `appConfig` export entirely. That breaks every
consumer with `"appConfig" is not exported by ".../navigation.js"`.

This builder writes navigation.js deterministically from
`project_schema.navigation` so the template contract is preserved every
run. Authoritative-path filter then keeps Phase 1/2 from overwriting it.

Pure module — no I/O, no LLM, no async.
"""
from __future__ import annotations

import json
import logging
import re
from typing import Any

logger = logging.getLogger(__name__)


def _coerce(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value.strip()
    return str(value).strip()


def _slugify_key(*parts: str) -> str:
    """Stable, JS-safe key from any text. `'Email Campaigns!' → 'email_campaigns'`.
    Falls back to 'item' if every part collapses to empty."""
    raw = "_".join(p for p in parts if p).lower()
    slug = re.sub(r"[^a-z0-9]+", "_", raw).strip("_")
    return slug or "item"


def _flatten_items(navigation: list[dict]) -> list[dict]:
    """Flatten the schema's `[{group, items: [{label, path, icon}]}]`
    into `[{key, label, icon, path}, ...]`. Group label is preserved as
    a path-key prefix so two different groups can have an item with the
    same display label without colliding on `key`. Drops items missing
    label or path. Dedupes on path (first-write-wins)."""
    out: list[dict] = []
    seen_paths: set[str] = set()
    for grp in navigation or []:
        if not isinstance(grp, dict):
            continue
        group_name = _coerce(grp.get("group"))
        for it in grp.get("items") or []:
            if not isinstance(it, dict):
                continue
            label = _coerce(it.get("label"))
            path = _coerce(it.get("path") or it.get("href"))
            icon = _coerce(it.get("icon")) or "Circle"
            if not label or not path:
                continue
            if path in seen_paths:
                continue
            seen_paths.add(path)
            key = _slugify_key(group_name, label) if group_name else _slugify_key(label)
            out.append({
                "key": key,
                "label": label,
                "icon": icon,
                "path": path,
            })
    return out


def build_admin_navigation_config(project_schema: dict) -> str:
    """Render navigation.js source matching the template's contract.

    Always emits all three named exports (navigation, modules, appConfig)
    even when the schema is empty — keeps consumers compiling. Returns
    a self-contained module string ready to write to disk.
    """
    nav_groups = project_schema.get("navigation") or []
    brand = (project_schema.get("brand") or {}).get("name") or "Admin Panel"
    flat_items = _flatten_items(nav_groups)

    nav_lines = ["export const navigation = ["]
    for it in flat_items:
        nav_lines.append("  {")
        nav_lines.append(f"    key: {json.dumps(it['key'])},")
        nav_lines.append(f"    label: {json.dumps(it['label'])},")
        nav_lines.append(f"    icon: {json.dumps(it['icon'])},")
        nav_lines.append(f"    path: {json.dumps(it['path'])},")
        nav_lines.append("  },")
    nav_lines.append("]")
    nav_block = "\n".join(nav_lines)

    # `import.meta.env.VITE_APP_NAME` MUST stay as a JS expression — it
    # is read at runtime by Vite. JSON-quoting would break the override.
    brand_js = json.dumps(brand)
    return f"""/**
 * Navigation Configuration
 *
 * Deterministic — generated by ai_engine from project_schema.navigation.
 * Sidebar.jsx, Header.jsx, LoginPage.jsx and other consumers import the
 * `navigation`, `modules`, and `appConfig` named exports below. Phase 1/2
 * LLM is forbidden from regenerating this file via the authoritative-paths
 * filter, so the consumer contract is stable across runs.
 */

{nav_block}

/**
 * Primary sidebar modules (top-level icon bar).
 */
export const modules = [
  {{ key: 'main', label: {brand_js}, icon: 'LayoutDashboard' }},
]

/**
 * App metadata used in the header and sidebar branding.
 */
export const appConfig = {{
  name: import.meta.env.VITE_APP_NAME || {brand_js},
  logo: null,
}}
"""
