"""Stage 6 — per-entity admin CRUD codegen.

Step 3.6 Part A wires the entire flow but defaults to ``mock=True`` so
no Anthropic credits are spent. Part B (when credits arrive) will set
``mock=False`` and let Claude generate real list / create / edit
pages.

Flow per entity
---------------
For each entity table:
  1. Build three prompts (list / create / edit) via the prompt modules.
  2. If mock=True: write a placeholder JSX that imports AuthGuard and
     explains itself. Skip the Claude call.
  3. If mock=False: call `call_claude_for_json` once per prompt,
     receive a file from the model, and write it to disk.
  4. Run the static validator over each emitted file; surface any
     issues in the result dict so the caller can log / re-prompt.

The mock pages are deliberately a step up from Step 3.5's stubs:
they import AuthGuard + listCollection and call the helper, which
proves the import contract is honoured without needing Claude.
"""
from __future__ import annotations

import logging
import os
from typing import Any

from app.services.admin_codegen_validator import (
    summarise_issues,
    validate_generated_crud_file,
)
from app.services.data_model import DataModel, TableDefinition
from app.services.prompts import (
    build_create_view_prompt,
    build_edit_view_prompt,
    build_list_view_prompt,
)

logger = logging.getLogger(__name__)


# ── Tunables ─────────────────────────────────────────────────────────

# Rough per-page cost — claude-sonnet-4-6 at ~$3/Mtok in + $15/Mtok out.
# A 4K-input / 3K-output page lands around ~$0.05. We log this BEFORE
# the call so a pipeline operator can see the budget the run will spend.
_EST_PAGE_COST_USD = 0.05

# Default model — picked to match the website page_codegen path.
_DEFAULT_MODEL = "claude-sonnet-4-6"


# ── Mock page generator ──────────────────────────────────────────────

def _mock_page_jsx(
    entity: TableDefinition,
    page_type: str,
    plan: dict,
) -> str:
    """A self-explanatory placeholder JSX file.

    The mock honours the SAME contract Claude will: 'use client',
    AuthGuard import, plus the page-specific db_admin helper
    (listCollection / createRow / updateRow). Validates the import
    contract without burning credits.
    """
    label_plural   = entity.plural_label or entity.name
    label_singular = entity.singular_label or entity.name
    field_count    = len(entity.fields)
    component_name = "".join(p.title() for p in entity.name.split("_"))

    # Per-page identifiers + imports — matches what the validator
    # expects for `page_type`.
    config = {
        "list":   ("ListPage", "listCollection", "()"),
        "create": ("NewPage",  "createRow",      "()"),
        "edit":   ("EditPage", "updateRow",      "({ params })"),
    }[page_type]
    suffix, helper, params_arg = config

    brand = (plan.get("branding") or {}).get("brand_name") or "Admin"

    return (
        '"use client";\n'
        '/* MOCK page generated by Step 3.6 Part A.\n'
        ' * Real CRUD UI will be generated by Claude in Part B.\n'
        ' * Imports AuthGuard + db_admin so the contract Claude will\n'
        ' * inherit is exercised even in mock mode.\n'
        ' */\n'
        'import { AuthGuard } from "@/components/AuthGuard.jsx";\n'
        f'import {{ {helper} }} from "@/lib/db_admin.js";\n'
        '\n'
        f'export default function {component_name}{suffix}{params_arg} {{\n'
        f'  // {helper} is referenced so the bundler ships it. The real\n'
        '  // component will use it; here it suppresses the\n'
        '  // unused-import warning in stricter builds.\n'
        f'  void {helper};\n'
        '  return (\n'
        '    <AuthGuard>\n'
        '      <div className="p-8 max-w-2xl">\n'
        f'        <h1 className="text-3xl font-bold mb-2">{label_plural}</h1>\n'
        f'        <p className="text-sm text-muted-foreground mb-6">{brand} admin</p>\n'
        '        <p className="text-muted-foreground mb-2">\n'
        f'          This is a MOCK page for the <code>{entity.name}</code> entity.\n'
        '        </p>\n'
        '        <p className="text-sm text-muted-foreground">\n'
        f'          Page type: <strong>{page_type}</strong>. ' \
        f'Entity: <code>{entity.name}</code> ({field_count} field' \
        f'{"" if field_count == 1 else "s"}).<br />\n'
        '          When Anthropic credits are available and\n'
        '          <code> ADMIN_CODEGEN_MOCK=false</code>, Claude will\n'
        f'          generate the real {page_type} UI for {label_singular} here.\n'
        '        </p>\n'
        '      </div>\n'
        '    </AuthGuard>\n'
        '  );\n'
        '}\n'
    )


# ── Real-Claude path ─────────────────────────────────────────────────

async def _call_claude_for_one_page(
    *,
    prompt: dict[str, str],
    anthropic_key: str,
    label: str,
) -> tuple[str | None, float]:
    """One Claude call → (file_content, actual_cost_usd).

    Returns ``(None, 0.0)`` on any failure so the caller can decide
    whether to fall back to the mock page or surface the issue.
    """
    # Lazy import — keeps mock-mode test imports cheap and avoids a
    # circular import via project_generator.
    from app.services.project_generator import call_claude_for_json

    try:
        result = await call_claude_for_json(
            system_prompt=prompt["system"],
            user_prompt=prompt["user"],
            api_key=anthropic_key,
            websocket=None,
            model=_DEFAULT_MODEL,
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning("admin_codegen %s: Claude call threw — %s", label, exc)
        return None, 0.0

    if not result or not result.get("files"):
        logger.warning("admin_codegen %s: empty result from Claude", label)
        return None, 0.0

    # Spec: exactly one file. If Claude returned more, use the first
    # whose path looks like the page route — anything else is content
    # Claude added uninvited (rare but possible).
    files = result["files"]
    first = files[0]
    raw_content = first.get("content")
    if not isinstance(raw_content, str) or not raw_content.strip():
        logger.warning(
            "admin_codegen %s: file came back with non-string content (%s)",
            label, type(raw_content).__name__,
        )
        return None, 0.0

    # Actual cost is unknown without parsing usage from the Anthropic
    # response — call_claude_for_json doesn't surface it today. For
    # Part B we'd thread it through; for Part A we report the estimate.
    return raw_content, _EST_PAGE_COST_USD


# ── Main entry ───────────────────────────────────────────────────────

async def generate_entity_crud(
    *,
    entity: TableDefinition,
    data_model: DataModel,
    admin_plan: dict,
    workspace_path: str,
    anthropic_key: str = "",
    mock: bool = True,
) -> dict[str, Any]:
    """Generate the 3 CRUD pages for one entity.

    Returns a dict with:
      • ``files_written``         — list of relative paths
      • ``claude_cost_estimate``  — sum of per-page budget estimates
      • ``claude_actual_cost``    — actual spend (0 when mock=True)
      • ``validation_errors``     — list of `{file, issues}` dicts for
                                    any file that failed the static
                                    validator
    """
    _ = data_model  # reserved for future cross-entity context

    slug = entity.name.replace("_", "-")
    pages: list[tuple[str, str, dict]] = [
        # (page_type,  rel_path,                                 prompt)
        ("list",   f"src/app/{slug}/page.jsx",        build_list_view_prompt(entity, admin_plan)),
        ("create", f"src/app/{slug}/new/page.jsx",    build_create_view_prompt(entity, admin_plan)),
        ("edit",   f"src/app/{slug}/[id]/page.jsx",   build_edit_view_prompt(entity, admin_plan)),
    ]

    files_written: list[str] = []
    validation_errors: list[dict[str, Any]] = []
    cost_estimate = 0.0
    cost_actual   = 0.0

    for page_type, rel_path, prompt in pages:
        label = f"{entity.name}/{page_type}"
        cost_estimate += _EST_PAGE_COST_USD

        if mock:
            content = _mock_page_jsx(entity, page_type, admin_plan)
        else:
            content, page_cost = await _call_claude_for_one_page(
                prompt=prompt,
                anthropic_key=anthropic_key,
                label=label,
            )
            cost_actual += page_cost
            if content is None:
                # Hard fail — caller can decide whether to retry.
                validation_errors.append({
                    "file":  rel_path,
                    "issues": ["claude returned no usable file"],
                })
                continue

        # Validate before writing — same check whether mock or real.
        issues = validate_generated_crud_file(
            content,
            expected_entity=entity.name,
            page_type=page_type,
        )
        if issues:
            logger.warning(
                "admin_codegen %s: validator flagged:\n%s",
                label, summarise_issues(issues),
            )
            validation_errors.append({"file": rel_path, "issues": issues})

        # Write even if validator complained — easier to inspect a
        # broken file than to recover from a missing one. Production
        # callers may choose to skip writes on errors; for the dry run
        # we want everything on disk.
        abs_path = os.path.join(workspace_path, rel_path)
        os.makedirs(os.path.dirname(abs_path), exist_ok=True)
        with open(abs_path, "w", encoding="utf-8") as fh:
            fh.write(content)
        files_written.append(rel_path)

    logger.info(
        "admin_codegen %s: %d files written (mock=%s, validator_errors=%d)",
        entity.name, len(files_written), mock, len(validation_errors),
    )

    return {
        "files_written":        files_written,
        "claude_cost_estimate": round(cost_estimate, 4),
        "claude_actual_cost":   round(cost_actual,   4),
        "validation_errors":    validation_errors,
    }
