"""
CI/CD Template Generator — produces Dockerfile, nginx.conf, .gitlab-ci.yml, Makefile
for generated projects before they are pushed to the repo.

Company standard: ucode/ops shared CI/CD, nginx-based frontend, Helm + K8s.
"""


def generate_dockerfile(stack: str = "react", node_version: int = 20) -> str:
    """Generate a Dockerfile matching the company standard.

    For frontend projects: multi-stage build with nginx.
    For Next.js: standalone build with Node server.
    """
    stack = (stack or "react").lower().strip()

    if stack == "nextjs":
        return f"""FROM node:{node_version}-alpine AS builder
RUN apk update && apk add yarn
WORKDIR /app
COPY . ./
RUN yarn install --network-timeout 1000000000
RUN NODE_OPTIONS=--max_old_space_size=4096 yarn build

FROM node:{node_version}-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
EXPOSE 3000
CMD ["node", "server.js"]
"""

    # React / Vue / Angular — nginx-based static build
    build_cmd = {
        "react": "yarn build",
        "vue": "yarn build",
        "angular": "yarn build -- --configuration production",
        "html-css": "",
    }.get(stack, "yarn build")

    if stack == "html-css":
        # Plain HTML — no build step
        return f"""FROM nginx:alpine
COPY . /build
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
"""

    return f"""FROM node:{node_version}-alpine AS builder
RUN apk update && apk add yarn
WORKDIR /app
COPY . ./
RUN yarn install --network-timeout 1000000000
RUN NODE_OPTIONS=--max_old_space_size=4096 yarn build

FROM nginx:alpine
COPY --from=builder /app/dist /build
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
"""


def generate_nginx_conf(is_admin: bool = False) -> str:
    """Generate nginx.conf for the project.

    Two variants:
    - Standard: simple SPA routing
    - Admin: full config with gzip, remoteEntry.js, worker processes
    """
    if is_admin:
        return """user  nginx;
worker_processes  1;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;
events {
  worker_connections  1024;
}
http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
  access_log  /var/log/nginx/access.log  main;
  sendfile        on;
  keepalive_timeout   65;
  server {
    gzip on;
    gzip_types      text/plain application/xml;
    gzip_proxied    no-cache no-store private expired auth;
    gzip_min_length 1000;
    listen       80;
    server_name  localhost;
    location / {
      root   /build;
      index  index.html;
      try_files $uri $uri/ /index.html;
    }
    location /assets/remoteEntry.js {
      root /build;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
      root   /usr/share/nginx/html;
    }
  }
}
"""

    return """server {
    listen 80;
    server_name _;

    root /build;
    index index.html;

    gzip on;
    gzip_types
        text/plain
        text/css
        application/javascript
        application/json
        application/xml
        image/svg+xml;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
"""


def generate_gitlab_ci() -> str:
    """Generate .gitlab-ci.yml using company shared CI/CD includes."""
    return """include:
  - project: 'ucode/ops/ci-cd'
    ref: master
    file: 'vault/vault.gitlab-ci.yml'

  - project: 'ucode/ops/ci-cd'
    ref: master
    file: 'frontend/ci.gitlab-ci.yml'

  - project: 'ucode/ops/ci-cd'
    ref: master
    file: 'frontend/cd.gitlab-ci.yml'

stages:
  - vault
  - build
  - deploy
"""


def generate_makefile(project_slug: str, registry_url: str = "gitlab.udevs.io:5050") -> str:
    """Generate a Makefile for the project."""
    return f"""# ─────────────────────────────────────────────────
#  {project_slug} — Makefile
#  Auto-generated by Lucid AI
# ─────────────────────────────────────────────────

APP_NAME    := {project_slug}
REGISTRY    := {registry_url}
IMAGE       := $(REGISTRY)/$(APP_NAME)
TAG         := $(shell git rev-parse --short HEAD 2>/dev/null || echo "latest")

.PHONY: install build dev test lint clean docker-build docker-push docker-run

# ── Development ──────────────────────────────────

install:
\tyarn install

build:
\tyarn build

dev:
\tyarn dev

test:
\tyarn test || true

lint:
\tyarn lint || true

clean:
\trm -rf node_modules .next dist out

# ── Docker ───────────────────────────────────────

docker-build:
\tdocker build -t $(IMAGE):$(TAG) -t $(IMAGE):latest .

docker-push: docker-build
\tdocker push $(IMAGE):$(TAG)
\tdocker push $(IMAGE):latest

docker-run:
\tdocker run --rm -p 80:80 $(IMAGE):latest
"""
