"""Phase-0 deterministic builders for the new landing-page flow.

Writes everything that doesn't need an LLM:
  • src/app/globals.css      — Tailwind directives + palette HSL CSS vars
  • src/app/layout.jsx       — root layout with Google Fonts from Brief
  • src/lib/design-system.js — minimal motion/container/section_padding tokens
  • src/components/ui/Reveal.jsx — scroll-triggered entrance wrapper

Header + footer are NOT written here anymore — they are generated by
landing_section_codegen.generate_layout_components() based on the Brief's
header_archetype + footer_archetype. We do still write deterministic STUB
fallbacks so layout.jsx imports never fail if codegen errored.
"""
from __future__ import annotations

import logging
import os
from typing import Any

logger = logging.getLogger(__name__)


# ── globals.css ──────────────────────────────────────────────────────

_GLOBALS_TEMPLATE = """@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {{
  :root {{
{palette_vars}
    --radius: 0.625rem;
  }}

  * {{
    @apply border-border;
  }}

  html {{
    scroll-behavior: smooth;
  }}

  body {{
    @apply bg-background text-foreground;
    font-family: var(--font-body, "{body_font}"), system-ui, -apple-system, sans-serif;
  }}

  h1, h2, h3, h4, h5, h6 {{
    font-family: var(--font-heading, "{heading_font}"), system-ui, sans-serif;
  }}

  /* Anchor jumps must clear sticky/fixed headers */
  section[id], div[id] {{
    scroll-margin-top: 5rem;
  }}

  /* Horizontal overflow is contained by the body wrapper so sticky
     elements (the marketing header) keep working. Setting overflow-x
     on html or body silently breaks `position: sticky`. */
  body {{
    overflow-x: clip;
  }}
}}
"""


def _palette_vars(palette: dict[str, str]) -> str:
    keys = ["background", "foreground", "primary", "secondary", "accent",
            "muted", "border", "card"]
    lines = []
    for k in keys:
        v = (palette.get(k) or "").strip()
        if not v:
            continue
        lines.append(f"    --{k}: {v};")
        if k == "background":
            lines.append(f"    --foreground-on-bg: {palette.get('foreground', '0 0% 10%')};")
    # Derived foregrounds for shadcn semantic pairs (best-effort — generated
    # palette never gives us these explicitly, so we mirror foreground/background).
    derived = {
        "primary-foreground":   palette.get("background", "0 0% 100%"),
        "secondary-foreground": palette.get("foreground", "0 0% 10%"),
        "accent-foreground":    palette.get("background", "0 0% 100%"),
        "muted-foreground":     palette.get("foreground", "0 0% 40%"),
        "card-foreground":      palette.get("foreground", "0 0% 10%"),
        "popover":              palette.get("card", "0 0% 100%"),
        "popover-foreground":   palette.get("foreground", "0 0% 10%"),
        "input":                palette.get("border", "0 0% 90%"),
        "ring":                 palette.get("primary", "220 90% 56%"),
        "destructive":          "0 84% 60%",
        "destructive-foreground": "0 0% 100%",
    }
    for k, v in derived.items():
        lines.append(f"    --{k}: {v};")
    return "\n".join(lines)


def write_landing_globals_css(workspace_path: str, brief: dict[str, Any]) -> str:
    palette = dict(brief.get("palette") or {})
    typo = dict(brief.get("typography") or {})
    css = _GLOBALS_TEMPLATE.format(
        palette_vars=_palette_vars(palette),
        heading_font=typo.get("heading_font", "Inter"),
        body_font=typo.get("body_font", "Inter"),
    )
    target = os.path.join(workspace_path, "src", "app", "globals.css")
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(css)
    return target


# ── layout.jsx (root) ────────────────────────────────────────────────

_LAYOUT_TEMPLATE = '''import "./globals.css";
{font_import}
import MarketingHeader from "@/components/layout/MarketingHeader";
import MarketingFooter from "@/components/layout/MarketingFooter";
import landing from "@/content/landing.json";

// Always pass `weight` — many serif/display fonts (Cormorant Garamond,
// Playfair Display, EB Garamond, etc.) are NOT variable on next/font and
// will fail the build with "Missing weight". Passing common weights for
// every font keeps the import safe across variable + static fonts.
const heading = {heading_var}({{
  subsets: ["latin"],
  variable: "--font-heading",
  weight: ["400", "500", "600", "700"],
  display: "swap",
}});
const body    = {body_var}({{
  subsets: ["latin"],
  variable: "--font-body",
  weight: ["400", "500", "600", "700"],
  display: "swap",
}});

export const metadata = {{
  title: landing.brand.name + " — " + landing.brand.tagline,
  description: landing.brand.description,
}};

export default function RootLayout({{ children }}) {{
  return (
    <html lang="en" className={{`${{heading.variable}} ${{body.variable}}`}}>
      <body className="bg-background text-foreground antialiased">
        <MarketingHeader />
        {{children}}
        <MarketingFooter />
      </body>
    </html>
  );
}}
'''


# Allowlist of Google Fonts we know exist + accept the common 400/500/600/700
# weight set we pass at the layout level. Brief sometimes suggests commercial
# fonts (Söhne, Founders Grotesk, GT America) that next/font/google rejects;
# we map those to the closest free equivalent so the build still succeeds.
_GOOGLE_FONT_ALLOWLIST = {
    "Inter", "Roboto", "Open_Sans", "Lato", "Montserrat", "Poppins",
    "Nunito", "Nunito_Sans", "Manrope", "Work_Sans", "DM_Sans",
    "IBM_Plex_Sans", "IBM_Plex_Serif", "IBM_Plex_Mono",
    "Space_Grotesk", "Space_Mono", "Plus_Jakarta_Sans",
    "Outfit", "Sora", "Figtree", "Public_Sans", "Onest",
    "Playfair_Display", "Lora", "Merriweather", "EB_Garamond",
    "Cormorant_Garamond", "Cormorant", "Crimson_Pro", "Crimson_Text",
    "Libre_Baskerville", "Libre_Caslon_Text", "Source_Serif_4",
    "Fraunces", "DM_Serif_Display", "DM_Serif_Text", "Bricolage_Grotesque",
    "Geist", "Geist_Mono", "JetBrains_Mono", "Roboto_Mono",
    "Archivo", "Archivo_Narrow", "Bebas_Neue", "Oswald", "Raleway",
    "Quicksand", "Karla", "Mulish", "Rubik", "Urbanist",
    "Cardo", "Spectral", "Vollkorn",
}

# Map common commercial / non-Google font names to the closest free equivalent.
_FONT_ALIASES = {
    "söhne": "Inter",
    "sohne": "Inter",
    "founders grotesk": "Space_Grotesk",
    "gt america": "Inter",
    "gt walsheim": "Manrope",
    "neue haas grotesk": "Inter",
    "neue haas unica": "Inter",
    "helvetica neue": "Inter",
    "helvetica": "Inter",
    "circular": "Manrope",
    "circular std": "Manrope",
    "graphik": "Inter",
    "söhne breit": "Inter",
    "national 2": "Inter",
    "tiempos": "Lora",
    "tiempos headline": "Playfair_Display",
    "söhne mono": "JetBrains_Mono",
    "akzidenz grotesk": "Inter",
}


def _font_var(name: str) -> str:
    """Normalize a font name for `next/font/google` import.

    `Playfair Display` → `Playfair_Display`. Falls back to Inter when the
    font isn't a real Google Font (commercial / made-up names) — this
    prevents next/font from failing the build with "Unknown font".
    """
    raw = (name or "Inter").strip()
    if not raw:
        return "Inter"

    aliased = _FONT_ALIASES.get(raw.lower())
    if aliased:
        return aliased

    cleaned = raw.replace(" ", "_")
    if cleaned in _GOOGLE_FONT_ALLOWLIST:
        return cleaned

    logger.info("landing_phase0: font %r not in Google Fonts allowlist — falling back to Inter", raw)
    return "Inter"


def write_landing_layout(workspace_path: str, brief: dict[str, Any]) -> str:
    typo = dict(brief.get("typography") or {})
    heading_var = _font_var(typo.get("heading_font", "Inter"))
    body_var = _font_var(typo.get("body_font", "Inter"))
    # When both fonts resolve to the same identifier, `import { X, X }` is a
    # SyntaxError in ESM — import it once and call the constructor twice.
    if heading_var == body_var:
        font_import = f'import {{ {heading_var} }} from "next/font/google";'
    else:
        font_import = f'import {{ {heading_var}, {body_var} }} from "next/font/google";'
    src = _LAYOUT_TEMPLATE.format(
        font_import=font_import,
        heading_var=heading_var,
        body_var=body_var,
    )
    app_dir = os.path.join(workspace_path, "src", "app")
    os.makedirs(app_dir, exist_ok=True)
    # Remove the skeleton's layout.js so Next.js doesn't see two entrypoints.
    for stale in ("layout.js", "layout.tsx"):
        sp = os.path.join(app_dir, stale)
        if os.path.exists(sp):
            try:
                os.remove(sp)
            except OSError:
                pass
    target = os.path.join(app_dir, "layout.jsx")
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(src)
    return target


# ── MarketingHeader.jsx ──────────────────────────────────────────────

_HEADER_SRC = '''"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import landing from "@/content/landing.json";

export default function MarketingHeader() {
  const [scrolled, setScrolled] = useState(false);
  const [open, setOpen] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 8);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const nav = landing.nav || [];
  const cta = landing.ctas?.primary;

  return (
    <header
      className={`sticky top-0 z-50 w-full transition-colors ${
        scrolled
          ? "bg-background/85 backdrop-blur border-b border-border"
          : "bg-transparent"
      }`}
    >
      <div className="container mx-auto flex h-16 items-center justify-between px-4 sm:px-6 lg:px-8">
        <Link href="/" className="text-lg font-semibold tracking-tight">
          {landing.brand?.name}
        </Link>

        <nav className="hidden items-center gap-8 md:flex">
          {nav.map((item) => (
            <a
              key={item.href}
              href={item.href}
              className="text-sm text-muted-foreground transition-colors hover:text-foreground"
            >
              {item.label}
            </a>
          ))}
        </nav>

        <div className="hidden md:flex">
          {cta?.label && (
            <a
              href={cta.href || "#contact"}
              className="inline-flex items-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-opacity hover:opacity-90"
            >
              {cta.label}
            </a>
          )}
        </div>

        <button
          aria-label="Open menu"
          onClick={() => setOpen((v) => !v)}
          className="md:hidden inline-flex h-9 w-9 items-center justify-center rounded-md border border-border"
        >
          <span className="sr-only">Menu</span>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M3 6h18M3 12h18M3 18h18" />
          </svg>
        </button>
      </div>

      {open && (
        <div className="md:hidden border-t border-border bg-background">
          <div className="container mx-auto flex flex-col gap-1 px-4 py-3">
            {nav.map((item) => (
              <a
                key={item.href}
                href={item.href}
                onClick={() => setOpen(false)}
                className="rounded px-2 py-2 text-sm text-foreground hover:bg-muted"
              >
                {item.label}
              </a>
            ))}
            {cta?.label && (
              <a
                href={cta.href || "#contact"}
                onClick={() => setOpen(false)}
                className="mt-2 inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground"
              >
                {cta.label}
              </a>
            )}
          </div>
        </div>
      )}
    </header>
  );
}
'''


# Alt stub: floating glass pill (lifestyle / hospitality / restaurant default).
# Visually distinct from solid-bar so the page doesn't look like every other
# generated site when Claude codegen fails to overwrite this stub.
_HEADER_SRC_PILL = '''"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import landing from "@/content/landing.json";

export default function MarketingHeader() {
  const [scrolled, setScrolled] = useState(false);
  const [open, setOpen] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 8);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const nav = landing.nav || [];
  const cta = landing.ctas?.primary;

  return (
    <header className="fixed top-0 left-0 right-0 z-50 transition-all duration-300">
      <div
        className={`mx-auto mt-4 flex h-14 max-w-6xl items-center justify-between rounded-full px-6 transition-all duration-300 ${
          scrolled
            ? "bg-background/90 backdrop-blur-md border border-border shadow-lg"
            : "bg-background/55 backdrop-blur-sm border border-border/40 shadow-sm"
        }`}
      >
        <Link href="/" className="text-lg font-semibold tracking-tight">
          {landing.brand?.name}
        </Link>

        <nav className="hidden items-center gap-7 md:flex">
          {nav.map((item) => (
            <a
              key={item.href}
              href={item.href}
              className="text-sm font-medium text-foreground/80 transition-colors hover:text-primary"
            >
              {item.label}
            </a>
          ))}
        </nav>

        <div className="hidden md:flex">
          {cta?.label && (
            <a
              href={cta.href || "#contact"}
              className="inline-flex h-9 items-center rounded-full bg-primary px-5 text-sm font-medium text-primary-foreground transition hover:opacity-90"
            >
              {cta.label}
            </a>
          )}
        </div>

        <button
          aria-label="Open menu"
          onClick={() => setOpen((v) => !v)}
          className="md:hidden inline-flex h-9 w-9 items-center justify-center rounded-full bg-background/80 backdrop-blur border border-border"
        >
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M3 6h18M3 12h18M3 18h18" />
          </svg>
        </button>
      </div>

      {open && (
        <div className="md:hidden absolute inset-x-4 top-20 rounded-2xl bg-background border border-border shadow-xl p-6 space-y-3">
          {nav.map((item) => (
            <a
              key={item.href}
              href={item.href}
              onClick={() => setOpen(false)}
              className="block rounded px-2 py-2 text-sm text-foreground hover:bg-muted"
            >
              {item.label}
            </a>
          ))}
          {cta?.label && (
            <a
              href={cta.href || "#contact"}
              onClick={() => setOpen(false)}
              className="mt-2 inline-flex w-full items-center justify-center rounded-full bg-primary px-4 py-2 text-sm font-medium text-primary-foreground"
            >
              {cta.label}
            </a>
          )}
        </div>
      )}
    </header>
  );
}
'''


# Alt stub: centered-logo (editorial / luxury / fashion / fine dining).
_HEADER_SRC_CENTERED = '''"use client";

import { useState } from "react";
import Link from "next/link";
import landing from "@/content/landing.json";

export default function MarketingHeader() {
  const [open, setOpen] = useState(false);
  const nav = landing.nav || [];
  const cta = landing.ctas?.primary;
  const half = Math.ceil(nav.length / 2);
  const left = nav.slice(0, half);
  const right = nav.slice(half);

  return (
    <header className="sticky top-0 z-50 bg-background border-b border-border">
      <div className="relative flex h-20 items-center justify-between px-6 lg:px-12">
        <nav className="hidden items-center gap-7 md:flex">
          {left.map((item) => (
            <a
              key={item.href}
              href={item.href}
              className="text-xs uppercase tracking-[0.2em] text-foreground/80 hover:text-primary transition-colors"
            >
              {item.label}
            </a>
          ))}
        </nav>

        <Link
          href="/"
          className="absolute left-1/2 -translate-x-1/2 text-2xl md:text-3xl font-bold tracking-tight"
        >
          {landing.brand?.name}
        </Link>

        <div className="hidden md:flex items-center gap-7">
          {right.map((item) => (
            <a
              key={item.href}
              href={item.href}
              className="text-xs uppercase tracking-[0.2em] text-foreground/80 hover:text-primary transition-colors"
            >
              {item.label}
            </a>
          ))}
          {cta?.label && (
            <a
              href={cta.href || "#contact"}
              className="inline-flex h-9 items-center rounded-full bg-primary px-4 text-xs font-medium uppercase tracking-widest text-primary-foreground hover:opacity-90 transition"
            >
              {cta.label}
            </a>
          )}
        </div>

        <button
          aria-label="Open menu"
          onClick={() => setOpen((v) => !v)}
          className="md:hidden inline-flex h-9 w-9 items-center justify-center rounded-md border border-border"
        >
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M3 6h18M3 12h18M3 18h18" />
          </svg>
        </button>
      </div>

      {open && (
        <div className="md:hidden border-t border-border bg-background">
          <div className="container mx-auto flex flex-col gap-1 px-4 py-3">
            {nav.map((item) => (
              <a
                key={item.href}
                href={item.href}
                onClick={() => setOpen(false)}
                className="rounded px-2 py-2 text-xs uppercase tracking-[0.2em] text-foreground hover:bg-muted"
              >
                {item.label}
              </a>
            ))}
            {cta?.label && (
              <a
                href={cta.href || "#contact"}
                onClick={() => setOpen(false)}
                className="mt-2 inline-flex items-center justify-center rounded-full bg-primary px-4 py-2 text-xs font-medium uppercase tracking-widest text-primary-foreground"
              >
                {cta.label}
              </a>
            )}
          </div>
        </div>
      )}
    </header>
  );
}
'''


_HEADER_STUBS_BY_ARCHETYPE = {
    "transparent-pill": _HEADER_SRC_PILL,
    "centered-logo":    _HEADER_SRC_CENTERED,
    "solid-bar":        _HEADER_SRC,
    # side-rail and mega-menu are too complex for stubs — fall back to the
    # solid-bar baseline if Claude codegen fails for those archetypes.
    "side-rail":        _HEADER_SRC,
    "mega-menu":        _HEADER_SRC,
}


def write_landing_header(workspace_path: str, brief: dict[str, Any] | None = None) -> str:
    """Write the Phase-0 stub header — picked from the Brief's archetype.

    Three distinct stubs ship by default (pill, centered, solid). Claude
    codegen still tries to overwrite this with a per-project version, but
    if codegen fails (rate limits, etc.), at least the stub matches the
    brief's chosen vibe instead of always defaulting to the white solid bar.
    """
    archetype = ""
    if brief:
        archetype = (brief.get("header_archetype") or "").strip().lower()
    src = _HEADER_STUBS_BY_ARCHETYPE.get(archetype, _HEADER_SRC)
    target = os.path.join(workspace_path, "src", "components", "layout", "MarketingHeader.jsx")
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(src)
    logger.info("write_landing_header: stub=%s", archetype or "default-solid-bar")
    return target


# ── MarketingFooter.jsx ──────────────────────────────────────────────

_FOOTER_SRC = '''import landing from "@/content/landing.json";
import { Mail, Phone, MapPin, Clock, Instagram, Facebook, Twitter, Linkedin, Youtube, Github } from "lucide-react";

const SOCIAL_ICONS = {
  instagram: Instagram,
  facebook: Facebook,
  twitter: Twitter,
  x: Twitter,
  linkedin: Linkedin,
  youtube: Youtube,
  github: Github,
};

export default function MarketingFooter() {
  const brand = landing.brand || {};
  const info = brand.business_info || {};
  const social = brand.social || [];
  const footer = landing.footer || {};
  const links = footer.links || [];
  const cta = landing.ctas?.primary;
  const year = new Date().getFullYear();

  return (
    <footer className="border-t border-border bg-card">
      <div className="container mx-auto px-4 py-14 sm:px-6 lg:px-8">
        <div className="grid gap-10 md:grid-cols-12">
          <div className="md:col-span-5">
            <div className="text-lg font-semibold tracking-tight">{brand.name}</div>
            <p className="mt-3 max-w-md text-sm leading-relaxed text-muted-foreground">
              {brand.description || brand.tagline}
            </p>
            {social.length > 0 && (
              <div className="mt-6 flex items-center gap-3">
                {social.map((s) => {
                  const Icon = SOCIAL_ICONS[String(s.label || s.platform || "").toLowerCase()] || Mail;
                  return (
                    <a
                      key={s.href || s.label}
                      href={s.href || "#"}
                      aria-label={s.label || "social"}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex h-9 w-9 items-center justify-center rounded-full border border-border text-muted-foreground transition-colors hover:border-primary hover:text-primary"
                    >
                      <Icon className="h-4 w-4" />
                    </a>
                  );
                })}
              </div>
            )}
          </div>

          <div className="md:col-span-3">
            <div className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">Explore</div>
            <ul className="mt-4 space-y-2">
              {links.map((l) => (
                <li key={l.href}>
                  <a href={l.href} className="text-sm text-foreground/80 transition-colors hover:text-primary">
                    {l.label}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          <div className="md:col-span-4 space-y-4">
            <div className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">Visit</div>
            {info.address && (
              <div className="flex items-start gap-3 text-sm text-foreground/80">
                <MapPin className="h-4 w-4 mt-0.5 text-primary shrink-0" />
                <span>{info.address}</span>
              </div>
            )}
            {info.phone && (
              <a href={`tel:${info.phone}`} className="flex items-center gap-3 text-sm text-foreground/80 transition-colors hover:text-primary">
                <Phone className="h-4 w-4 text-primary shrink-0" />
                <span>{info.phone}</span>
              </a>
            )}
            {info.email && (
              <a href={`mailto:${info.email}`} className="flex items-center gap-3 text-sm text-foreground/80 transition-colors hover:text-primary">
                <Mail className="h-4 w-4 text-primary shrink-0" />
                <span>{info.email}</span>
              </a>
            )}
            {info.hours && (
              <div className="flex items-start gap-3 text-sm text-foreground/80">
                <Clock className="h-4 w-4 mt-0.5 text-primary shrink-0" />
                <span className="whitespace-pre-line">{info.hours}</span>
              </div>
            )}
            {cta?.label && (
              <a
                href={cta.href || "#contact"}
                className="mt-2 inline-flex items-center justify-center rounded-md bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground transition-opacity hover:opacity-90"
              >
                {cta.label}
              </a>
            )}
          </div>
        </div>

        <div className="mt-12 flex flex-col gap-3 border-t border-border pt-6 sm:flex-row sm:items-center sm:justify-between">
          <div className="text-xs text-muted-foreground">
            © {year} {brand.name}. All rights reserved.
          </div>
          <div className="text-xs text-muted-foreground">
            {brand.tagline}
          </div>
        </div>
      </div>
    </footer>
  );
}
'''


def write_landing_footer(workspace_path: str) -> str:
    target = os.path.join(workspace_path, "src", "components", "layout", "MarketingFooter.jsx")
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(_FOOTER_SRC)
    return target


# ── design-system.js (minimal) ───────────────────────────────────────

_DS_SRC = '''/**
 * Minimal design-system tokens for landing pages.
 *
 * Sections write their own Tailwind classes. This file only exposes the
 * site-wide invariants: container width, vertical rhythm, and motion.
 */
export const ds = {
  container: "container mx-auto px-4 sm:px-6 lg:px-8",
  section_padding: "py-16 sm:py-20 lg:py-24",
  heading: "text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight",
  subheading: "mt-4 text-base sm:text-lg text-muted-foreground",
  motion: {
    transition: "transition-colors duration-200 ease-out",
    hover: "hover:opacity-90",
  },
};

export default ds;
'''


def write_landing_design_system(workspace_path: str) -> str:
    target = os.path.join(workspace_path, "src", "lib", "design-system.js")
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(_DS_SRC)
    return target


# ── Reveal.jsx (scroll-triggered entrance) ───────────────────────────

_REVEAL_SRC = '''"use client";

import { useEffect, useRef, useState } from "react";

const VARIANTS = {
  "fade-up":    { hidden: "opacity-0 translate-y-6",  shown: "opacity-100 translate-y-0" },
  "fade-down":  { hidden: "opacity-0 -translate-y-6", shown: "opacity-100 translate-y-0" },
  "fade-left":  { hidden: "opacity-0 translate-x-6",  shown: "opacity-100 translate-x-0" },
  "fade-right": { hidden: "opacity-0 -translate-x-6", shown: "opacity-100 translate-x-0" },
  "fade":       { hidden: "opacity-0",                shown: "opacity-100" },
  "scale":      { hidden: "opacity-0 scale-95",       shown: "opacity-100 scale-100" },
};

/**
 * Scroll-triggered entrance wrapper. Drop into any section to reveal
 * its children when they enter the viewport. Stagger groups with the
 * `delay` prop (milliseconds).
 */
export default function Reveal({
  children,
  as: As = "div",
  variant = "fade-up",
  delay = 0,
  duration = 700,
  className = "",
  once = true,
}) {
  const ref = useRef(null);
  const [shown, setShown] = useState(false);
  const v = VARIANTS[variant] || VARIANTS["fade-up"];

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    if (typeof IntersectionObserver === "undefined") {
      setShown(true);
      return;
    }
    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) {
            setShown(true);
            if (once) io.disconnect();
          } else if (!once) {
            setShown(false);
          }
        });
      },
      { threshold: 0.12, rootMargin: "0px 0px -40px 0px" }
    );
    io.observe(el);
    return () => io.disconnect();
  }, [once]);

  return (
    <As
      ref={ref}
      style={{ transitionDelay: `${delay}ms`, transitionDuration: `${duration}ms` }}
      className={`transition-all ease-out will-change-transform ${shown ? v.shown : v.hidden} ${className}`}
    >
      {children}
    </As>
  );
}
'''


def write_landing_reveal(workspace_path: str) -> str:
    target = os.path.join(workspace_path, "src", "components", "ui", "Reveal.jsx")
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(_REVEAL_SRC)
    return target


# ── Orchestrating helper ─────────────────────────────────────────────

def run_landing_phase0(workspace_path: str, brief: dict[str, Any]) -> dict[str, str]:
    """Write all Phase-0 files for the new landing flow.

    Returns {file_label: written_path}. Raises on filesystem errors so the
    caller can decide whether to abort generation.
    """
    paths = {
        "globals_css":  write_landing_globals_css(workspace_path, brief),
        "layout":       write_landing_layout(workspace_path, brief),
        "header":       write_landing_header(workspace_path, brief),
        "footer":       write_landing_footer(workspace_path),
        "design_system": write_landing_design_system(workspace_path),
        "reveal":       write_landing_reveal(workspace_path),
    }
    logger.info("run_landing_phase0: wrote %d files", len(paths))
    return paths
