"""Per-project Supabase provisioning orchestrator.

Owns the full lifecycle for the customer's isolated Supabase project:
  1. Call Mgmt API → create project (under Lucid's Pro org)
  2. Poll until ACTIVE_HEALTHY
  3. Encrypt anon_key / service_key / db_password (AES-256-CBC, wire-compat
     with frontend/src/lib/crypto.js)
  4. Upsert into Lucid central DB's ``supabase_projects`` table
  5. Generate stack-correct client + env files for the user's project

Step 2 deliberately does NOT apply any business-domain migrations. Those
(`gen_site_config`, `gen_section`, `gen_entity_row`, etc.) belong to step 3
where the schema → DB mapping lives. Step 2 is provision-only, so the
provisioned project is empty (auth.users + storage only) until step 3 runs.
"""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from typing import Any

from app.config import settings
from app.services.crypto import encrypt
from app.services.supabase_mgmt import (
    ProvisionedProject,
    SupabaseMgmtError,
    create_project,
    delete_project,
    wait_until_ready,
)
from app.supabase_client import managed_admin_client

logger = logging.getLogger(__name__)


# Project-name sanitization: Supabase Mgmt API accepts a fairly liberal set,
# but downstream URL routing prefers slugs — strip anything non-alphanumeric/dash.
_NAME_SANITIZE = re.compile(r"[^A-Za-z0-9 _\-]")
_NAME_MAX_LEN = 60  # Mgmt API caps at 64; keep headroom for the user-id prefix.


@dataclass
class ProvisioningResult:
    """What the generation pipeline gets back. Only safe-to-log values are
    plain; secrets are returned alongside but should be passed straight into
    the generated app's env file or the encrypted storage row."""
    ref: str
    url: str
    anon_key: str
    service_key: str
    region: str
    db_row_id: str
    method: str = "rest"


def _canonical_project_name(*, user_id: str, project_slug: str) -> str:
    """Build a Supabase project name like '14fdaeb5-stonemill-bakery'.
    User-id prefix prevents naming collisions across customers; slug keeps
    it grep-able in the dashboard."""
    uid_prefix = (user_id or "").replace("-", "")[:8] or "user"
    raw_slug = (project_slug or "project").lower()
    sanitized = _NAME_SANITIZE.sub("-", raw_slug).strip("-") or "project"
    name = f"{uid_prefix}-{sanitized}"
    return name[:_NAME_MAX_LEN]


def _generate_nextjs_client_file() -> str:
    """src/lib/supabase/client.js — browser client for Next.js apps.
    Uses NEXT_PUBLIC_* env vars and @supabase/supabase-js (already in every
    skeleton's package.json). The full @supabase/ssr server-action pattern
    can be added later as a separate file without touching this one — this
    keeps the dependency surface to a single package."""
    return (
        "import { createClient } from '@supabase/supabase-js';\n"
        "\n"
        "export const supabase = createClient(\n"
        "  process.env.NEXT_PUBLIC_SUPABASE_URL,\n"
        "  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,\n"
        ");\n"
    )


def _generate_vite_client_file() -> str:
    """src/lib/supabase/client.js — Vite/React. Uses import.meta.env.VITE_*."""
    return (
        "import { createClient } from '@supabase/supabase-js';\n"
        "\n"
        "export const supabase = createClient(\n"
        "  import.meta.env.VITE_SUPABASE_URL,\n"
        "  import.meta.env.VITE_SUPABASE_ANON_KEY,\n"
        ");\n"
    )


def _generate_env_file(*, stack: str, supabase_url: str, anon_key: str) -> str:
    """Stack-correct .env.local snippet. Note: anon key is safe to ship in a
    public env var (RLS protects data); service key NEVER goes here."""
    if "next" in (stack or "").lower():
        return (
            "# Auto-generated by Lucid AI — Supabase credentials\n"
            f"NEXT_PUBLIC_SUPABASE_URL={supabase_url}\n"
            f"NEXT_PUBLIC_SUPABASE_ANON_KEY={anon_key}\n"
        )
    return (
        "# Auto-generated by Lucid AI — Supabase credentials\n"
        f"VITE_SUPABASE_URL={supabase_url}\n"
        f"VITE_SUPABASE_ANON_KEY={anon_key}\n"
    )


def generate_client_files(*, stack: str, supabase_url: str, anon_key: str) -> dict[str, str]:
    """Return {relative_path: file_contents} for all client files the user's
    generated app needs. Caller writes them into the workspace at the correct
    paths.

    Kept stack-aware so we don't ship Vite-style imports into a Next.js project
    (the prior bug in the frontend's provision.js)."""
    stack_l = (stack or "").lower()
    if "next" in stack_l:
        return {
            "src/lib/supabase/client.js": _generate_nextjs_client_file(),
            ".env.local": _generate_env_file(
                stack=stack, supabase_url=supabase_url, anon_key=anon_key,
            ),
        }
    # Vite / React / Vue all use import.meta.env.VITE_* by convention.
    return {
        "src/lib/supabase/client.js": _generate_vite_client_file(),
        ".env.local": _generate_env_file(
            stack=stack, supabase_url=supabase_url, anon_key=anon_key,
        ),
    }


async def _store_credentials(
    *,
    user_id: str,
    platform_project_id: str | None,
    project_slug: str,
    provisioned: ProvisionedProject,
) -> str:
    """Upsert the encrypted credentials into Lucid's central supabase_projects
    table. Uses the admin client because this is a server-to-server call
    during generation (no user JWT context). Returns the row id."""
    enc_anon = encrypt(provisioned.anon_key)
    enc_service = encrypt(provisioned.service_key)
    enc_db = encrypt(provisioned.db_password)

    payload: dict[str, Any] = {
        "user_id": user_id,
        "project_id": platform_project_id,
        "project_slug": project_slug,
        "supabase_ref": provisioned.ref,
        "supabase_url": provisioned.url,
        "anon_key_enc": enc_anon.encrypted,
        "anon_key_iv": enc_anon.iv,
        "service_key_enc": enc_service.encrypted,
        "service_key_iv": enc_service.iv,
        "db_password_enc": enc_db.encrypted,
        "db_password_iv": enc_db.iv,
        "region": provisioned.region,
        "status": "ACTIVE",
    }

    async with managed_admin_client() as client:
        # Upsert on (user_id, project_id) — re-provisioning the same logical
        # project replaces the old row. The unique constraint matches the
        # one defined in supabase/migrations/008_supabase_projects.sql.
        result = await client.table("supabase_projects").upsert(
            payload, on_conflict="user_id,project_id",
        ).execute()
        rows = getattr(result, "data", None) or []
        if not rows:
            raise SupabaseMgmtError(
                "supabase_projects upsert returned no rows",
                context={"ref": provisioned.ref, "user_id": user_id},
            )
        row_id = str(rows[0].get("id", ""))
        if not row_id:
            raise SupabaseMgmtError(
                "supabase_projects upsert returned a row without id",
                context={"ref": provisioned.ref, "row": rows[0]},
            )
        return row_id


async def provision_for_project(
    *,
    user_id: str,
    project_slug: str,
    platform_project_id: str | None = None,
    region: str | None = None,
    plan: str = "free",
    wait_ready_timeout: float = 180.0,
) -> ProvisioningResult:
    """End-to-end: create + wait + encrypt + store. Generation pipeline calls
    this once per generated app. Returns enough for the caller to also write
    client files into the workspace.

    On any partial failure (created project but couldn't store creds), we
    delete the project to avoid orphaned billable resources. The caller
    sees a single SupabaseMgmtError with a context describing where it
    failed.
    """
    if not user_id:
        raise SupabaseMgmtError("user_id is required", context={"project_slug": project_slug})
    if not settings.SUPABASE_MGMT_TOKEN or not settings.SUPABASE_MGMT_ORG_REF:
        raise SupabaseMgmtError(
            "Supabase provisioning is not configured. Set SUPABASE_MGMT_TOKEN "
            "and SUPABASE_MGMT_ORG_REF in ai_engine/.env.",
        )

    name = _canonical_project_name(user_id=user_id, project_slug=project_slug)
    logger.info("Provisioning Supabase project name=%s plan=%s region=%s", name, plan, region or settings.SUPABASE_DEFAULT_REGION)

    provisioned = await create_project(name=name, region=region, plan=plan)
    try:
        await wait_until_ready(provisioned.ref, timeout_seconds=wait_ready_timeout)
    except SupabaseMgmtError as exc:
        logger.error("Provision %s failed during readiness wait: %s", provisioned.ref, exc)
        # Best-effort cleanup — don't mask the original error if delete fails.
        try:
            await delete_project(provisioned.ref)
        except SupabaseMgmtError as del_exc:
            logger.warning("Cleanup delete also failed for %s: %s", provisioned.ref, del_exc)
        raise

    try:
        row_id = await _store_credentials(
            user_id=user_id,
            platform_project_id=platform_project_id,
            project_slug=project_slug,
            provisioned=provisioned,
        )
    except Exception as exc:
        logger.error(
            "Provision %s succeeded but credential storage failed: %s. "
            "Deleting orphaned project to avoid billing.", provisioned.ref, exc,
        )
        try:
            await delete_project(provisioned.ref)
        except SupabaseMgmtError as del_exc:
            logger.warning("Cleanup delete also failed for %s: %s", provisioned.ref, del_exc)
        raise

    logger.info(
        "Supabase provisioned for user=%s slug=%s ref=%s row_id=%s",
        user_id, project_slug, provisioned.ref, row_id,
    )
    return ProvisioningResult(
        ref=provisioned.ref,
        url=provisioned.url,
        anon_key=provisioned.anon_key,
        service_key=provisioned.service_key,
        region=provisioned.region,
        db_row_id=row_id,
    )
