// ─────────────────────────────────────────────────────────────────────────────
// Template Registry
// ─────────────────────────────────────────────────────────────────────────────

export const TEMPLATES = {
  'react-admin': {
    repo: 'LucidSoftware-tech/lucid-template-react-admin',
    label: 'React Admin Panel',
    stack: 'react',
    projectTypes: ['admin-panel', 'dashboard', 'crm', 'erp']
  },
  'nextjs-website': {
    repo: 'LucidSoftware-tech/lucid-template-nextjs-website',
    label: 'Next.js Website',
    stack: 'nextjs',
    projectTypes: ['website', 'landing', 'saas', 'ecommerce', 'blog', 'portfolio']
  },
  'vue-admin': {
    repo: 'LucidSoftware-tech/lucid-template-vue-admin',
    label: 'Vue Admin / Website',
    stack: 'vue',
    projectTypes: ['admin-panel', 'dashboard', 'website', 'crm']
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Template Selector
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Selects the best-matching template based on explicit stack choice or project type.
 *
 * @param {string} stack       - One of 'react' | 'vue' | 'nextjs' | undefined
 * @param {string} projectType - e.g. 'dashboard', 'website', 'saas', etc.
 * @returns {object}           - A template descriptor from TEMPLATES
 */
export function selectTemplate(stack, projectType) {
  // Explicit stack override takes highest priority
  if (stack === 'react') return TEMPLATES['react-admin']
  if (stack === 'vue')   return TEMPLATES['vue-admin']
  if (stack === 'nextjs') return TEMPLATES['nextjs-website']

  // Auto-select based on project type
  if (['website', 'landing', 'saas', 'ecommerce', 'blog', 'portfolio'].includes(projectType))
    return TEMPLATES['nextjs-website']

  if (['admin-panel', 'dashboard', 'crm', 'erp'].includes(projectType))
    return TEMPLATES['react-admin']

  // Default fallback
  return TEMPLATES['nextjs-website']
}

// ─────────────────────────────────────────────────────────────────────────────
// Clone Service
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Clones a Lucid template into a new private GitHub repository under the
 * LucidSoftware-tech organisation using the GitHub REST API.
 *
 * Flow:
 *   1. Fetch the template repo file tree (recursive)
 *   2. Create a new private repo in the org
 *   3. Fetch every blob's base64 content from the template
 *   4. Push all files in a single initial commit on `main`
 *
 * @param {object} template      - Template descriptor (from TEMPLATES / selectTemplate)
 * @param {string} newRepoName   - Desired name for the new repository
 * @param {string} githubToken   - GitHub PAT with repo + org scopes
 * @returns {Promise<{repoUrl: string, repoName: string, cloneUrl: string, template: string}>}
 */
export async function cloneTemplate(template, newRepoName, githubToken) {
  const headers = {
    Authorization: `Bearer ${githubToken}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28'
  }

  // ── Step 1: Fetch the template repo's full file tree ──────────────────────
  const treeRes = await fetch(
    `https://api.github.com/repos/${template.repo}/git/trees/main?recursive=1`,
    { headers }
  )
  if (!treeRes.ok) {
    const err = await treeRes.json()
    throw new Error(`Failed to fetch template tree: ${err.message}`)
  }
  const tree = await treeRes.json()

  // ── Step 2: Create a new private repo under the org ───────────────────────
  const createRes = await fetch(
    `https://api.github.com/orgs/LucidSoftware-tech/repos`,
    {
      method: 'POST',
      headers,
      body: JSON.stringify({
        name: newRepoName,
        private: true,
        auto_init: false,
        description: `Generated by Lucid from ${template.label}`
      })
    }
  )
  const newRepo = await createRes.json()
  if (!createRes.ok) throw new Error(`Repo creation failed: ${newRepo.message}`)

  // ── Step 3: Fetch blob contents for every file in the template ────────────
  const files = tree.tree.filter(f => f.type === 'blob')

  const fileContents = await Promise.all(
    files.map(async (file) => {
      const res = await fetch(
        `https://api.github.com/repos/${template.repo}/contents/${file.path}`,
        { headers }
      )
      const data = await res.json()
      return { path: file.path, content: data.content, encoding: 'base64' }
    })
  )

  // ── Step 4: Build and push the initial commit ─────────────────────────────

  // 4a. Create a blob in the new repo for each file
  const blobs = await Promise.all(
    fileContents.map(async (file) => {
      const blobRes = await fetch(
        `https://api.github.com/repos/LucidSoftware-tech/${newRepoName}/git/blobs`,
        {
          method: 'POST',
          headers,
          body: JSON.stringify({
            content: file.content,
            encoding: 'base64'
          })
        }
      )
      const blob = await blobRes.json()
      return { path: file.path, mode: '100644', type: 'blob', sha: blob.sha }
    })
  )

  // 4b. Create a git tree from all blobs
  const newTreeRes = await fetch(
    `https://api.github.com/repos/LucidSoftware-tech/${newRepoName}/git/trees`,
    {
      method: 'POST',
      headers,
      body: JSON.stringify({ tree: blobs })
    }
  )
  const newTree = await newTreeRes.json()
  if (!newTreeRes.ok) throw new Error(`Tree creation failed: ${newTree.message}`)

  // 4c. Create the initial commit (no parents — empty repo)
  const commitRes = await fetch(
    `https://api.github.com/repos/LucidSoftware-tech/${newRepoName}/git/commits`,
    {
      method: 'POST',
      headers,
      body: JSON.stringify({
        message: 'chore: init from Lucid template',
        tree: newTree.sha,
        parents: []
      })
    }
  )
  const commit = await commitRes.json()
  if (!commitRes.ok) throw new Error(`Commit creation failed: ${commit.message}`)

  // 4d. Point the main branch ref at the new commit
  const refRes = await fetch(
    `https://api.github.com/repos/LucidSoftware-tech/${newRepoName}/git/refs`,
    {
      method: 'POST',
      headers,
      body: JSON.stringify({
        ref: 'refs/heads/main',
        sha: commit.sha
      })
    }
  )
  if (!refRes.ok) {
    const refErr = await refRes.json()
    throw new Error(`Ref creation failed: ${refErr.message}`)
  }

  // ── Return a summary of the newly created repository ─────────────────────
  return {
    repoUrl: newRepo.html_url,
    repoName: newRepoName,
    cloneUrl: newRepo.clone_url,
    template: template.label
  }
}
