"""Run the data-model planner against the 5 fixture website plans.

Outputs a markdown document with the proposed DataModel for each
plan. Pipe to `docs/DATA_MODEL_PROPOSALS_SAMPLE.md` for the durable
reference, or just stdout-inspect during development.

Usage:
    docker exec -e OPENHANDS_SUPPRESS_BANNER=1 lucid-ai-ai_engine-1 \\
        python scripts/show_data_model_proposals.py \\
        > docs/DATA_MODEL_PROPOSALS_SAMPLE.md

Costs ~$0.005 per run (5 Gemini Flash calls).
"""
from __future__ import annotations

import asyncio
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


def _load_env_file(path: str) -> None:
    if not os.path.exists(path):
        return
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


_load_env_file(str(Path(__file__).resolve().parents[2] / ".env"))

from app.services.data_model_planner import plan_data_model  # noqa: E402


FIXTURES = Path(__file__).resolve().parents[1] / "tests" / "fixtures" / "website_plans"


PROFILES = [
    {
        "label": "Restaurant — Trattoria Bianca",
        "plan_file": "restaurant_plan.json",
        "intent": {
            "business_category": "restaurant",
            "geographic_specifics": "Brooklyn, NY",
            "tone": "warm",
        },
        "purpose": {"primary_purpose": "brand_awareness", "target_audience": "b2c_consumers"},
    },
    {
        "label": "E-commerce — Lens & Iron (vintage cameras)",
        "plan_file": "ecommerce_plan.json",
        "intent": {"business_category": "ecommerce", "tone": "curated"},
        "purpose": {"primary_purpose": "conversion", "target_audience": "b2c_consumers"},
    },
    {
        "label": "Blog — Slow Compile (tech blog)",
        "plan_file": "blog_plan.json",
        "intent": {"business_category": "content", "tone": "personal"},
        "purpose": {"primary_purpose": "brand_awareness", "target_audience": "developers"},
    },
    {
        "label": "Portfolio — Marta Reis (photographer)",
        "plan_file": "portfolio_plan.json",
        "intent": {"business_category": "creative", "tone": "minimalist"},
        "purpose": {"primary_purpose": "brand_awareness", "target_audience": "b2b_clients"},
    },
    {
        "label": "SaaS landing — Cortex Analytics",
        "plan_file": "saas_landing_plan.json",
        "intent": {"business_category": "saas", "tone": "professional"},
        "purpose": {"primary_purpose": "conversion", "target_audience": "b2b_decision_makers"},
    },
]


async def main() -> int:
    print("# Data model proposals (sample)")
    print()
    print(
        "Auto-generated by `scripts/show_data_model_proposals.py` against "
        "the 5 fixture plans in `tests/fixtures/website_plans/`. Each block "
        "shows what `plan_data_model()` returned from a real Gemini Flash "
        "call. Refresh after any change to the prompt:"
    )
    print()
    print("```bash")
    print(
        "docker exec -e OPENHANDS_SUPPRESS_BANNER=1 lucid-ai-ai_engine-1 \\\n"
        "    python scripts/show_data_model_proposals.py \\\n"
        "    > docs/DATA_MODEL_PROPOSALS_SAMPLE.md"
    )
    print("```")
    print()

    for profile in PROFILES:
        plan = json.loads((FIXTURES / profile["plan_file"]).read_text())
        model = await plan_data_model(
            website_plan=plan,
            intent=profile["intent"],
            purpose_data=profile["purpose"],
            gemini_key=os.environ.get("GOOGLE_API_KEY", ""),
            project_id=f"sample-{profile['plan_file']}",
        )

        print(f"## {profile['label']}")
        print()
        print(f"**Tables ({len(model.tables)})**: "
              f"{', '.join(t.name for t in model.tables) or '_none_'}  ")
        print(f"**Singletons ({len(model.singletons)})**: "
              f"{', '.join(model.singletons.keys()) or '_none_'}")
        print()
        print("```json")
        print(model.model_dump_json(indent=2))
        print("```")
        print()

    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
