"""pipeline/step5_direct.py — Single-call direct-API edit path.

Used by the edit-mode router when:

  • the target repo was generated by our platform (we know the layout,
    conventions, and TEMPLATE_MANIFEST), AND
  • Gemini's exploration identified a small, concrete set of files
    (``files_estimate ≤ 3``) for a simple task type, AND
  • the task is a surgical edit, not a multi-file redesign.

In that regime the iterative Claude Code SDK wastes tokens accumulating
tool-use context over ~10 turns to do work that fits in a single
``/v1/messages`` call:

    input  = files_content + manifest slice + task
    output = tool_use(apply_edits, edits=[{path, old_string, new_string}, ...])

Compared to the SDK path this routinely cuts per-edit tokens by 80–95 %.

Failure modes bubble up as ``False`` so the orchestrator can fall back to
the agentic SDK path without the user seeing an error:

  • Claude didn't call the tool at all (stop_reason != "tool_use")
  • Returned JSON doesn't match the schema
  • Any ``old_string`` isn't found in the target file (stale context)
  • Target file would escape the workspace
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from typing import Any, Optional

import httpx
from fastapi import WebSocket

logger = logging.getLogger("lucid.step5_direct")


_ANTHROPIC_URL = "https://api.anthropic.com/v1/messages"

# Upper bound per file so one huge generated file can't blow the context.
# 24 KB is ~600 lines of formatted JSX — covers every real component we ship.
_MAX_FILE_CHARS = 24_000

# Never read more than this much total file content in one call.
# At ~100 chars/token this leaves plenty of head-room under Claude's 200 K
# context window while keeping the bill predictable.
_MAX_TOTAL_CHARS = 90_000

# Hard cap on how many files the direct path will read. Matches the
# router's ``files_estimate ≤ 3`` gate with one spare slot for an import
# the plan didn't name.
_MAX_FILES = 4


# ── Tool schema — forces Claude to return a typed edit list ──────────────

_APPLY_EDITS_TOOL: dict[str, Any] = {
    "name": "apply_edits",
    "description": (
        "Apply a precise list of edits to workspace files. Each edit is an "
        "exact string replacement in a single file. Returns control to the "
        "build pipeline immediately after — no further tool calls needed."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "edits": {
                "type": "array",
                "description": (
                    "Ordered list of replacements. Each `old_string` MUST "
                    "appear literally and uniquely in the target file."
                ),
                "items": {
                    "type": "object",
                    "properties": {
                        "path": {
                            "type": "string",
                            "description": "Repo-relative file path.",
                        },
                        "old_string": {
                            "type": "string",
                            "description": (
                                "Exact substring to replace. Include enough "
                                "context to be unique. Empty string means "
                                "create a new file with `new_string` as its "
                                "entire contents."
                            ),
                        },
                        "new_string": {
                            "type": "string",
                            "description": "Replacement text.",
                        },
                    },
                    "required": ["path", "old_string", "new_string"],
                },
            },
            "summary": {
                "type": "string",
                "description": "One-sentence description of what changed.",
            },
        },
        "required": ["edits"],
    },
}


# ── File loading ─────────────────────────────────────────────────────────

def _load_files(
    workspace_path: str,
    rel_paths: list[str],
) -> tuple[dict[str, str], list[str]]:
    """Read up to ``_MAX_FILES`` files from ``rel_paths``.

    Returns ``(loaded, skipped)`` where ``loaded[path] = content`` and
    ``skipped`` names files that were dropped (too big, missing, or
    outside the workspace). Order is preserved so the first few files the
    caller listed get priority under the total-size cap.
    """
    workspace_real = os.path.realpath(workspace_path)
    loaded: dict[str, str] = {}
    skipped: list[str] = []
    total_chars = 0

    for rel in rel_paths:
        if len(loaded) >= _MAX_FILES:
            skipped.append(rel)
            continue
        if not rel or not isinstance(rel, str):
            continue
        # Path traversal guard — mirror the write-path check.
        abs_path = os.path.realpath(os.path.join(workspace_path, rel))
        if not (abs_path == workspace_real or abs_path.startswith(workspace_real + os.sep)):
            skipped.append(rel)
            continue
        if not os.path.isfile(abs_path):
            skipped.append(rel)
            continue
        try:
            with open(abs_path, "r", encoding="utf-8", errors="replace") as fh:
                content = fh.read()
        except Exception as exc:
            logger.warning("step5_direct: cannot read %s: %s", rel, exc)
            skipped.append(rel)
            continue
        if len(content) > _MAX_FILE_CHARS:
            skipped.append(rel)
            continue
        if total_chars + len(content) > _MAX_TOTAL_CHARS:
            skipped.append(rel)
            continue
        loaded[rel] = content
        total_chars += len(content)

    return loaded, skipped


# ── Edit application ─────────────────────────────────────────────────────

def _apply_edit(content: str, old_string: str, new_string: str) -> tuple[str, bool]:
    """Apply one edit. Returns ``(new_content, ok)``.

    An empty ``old_string`` means "create this file" — caller treats it
    that way. For non-empty old_string the match must be unique; if
    ``old_string`` appears zero or multiple times we bail so a stray
    replacement doesn't silently corrupt the file.
    """
    if old_string == "":
        return new_string, True
    occurrences = content.count(old_string)
    if occurrences == 0:
        return content, False
    if occurrences > 1:
        return content, False
    return content.replace(old_string, new_string, 1), True


# ── Public entry point ───────────────────────────────────────────────────

async def execute_direct_edit(
    task: str,
    workspace_path: str,
    api_key: str,
    classification: dict,
    plan: str,
    relevant_files: list[str],
    websocket: WebSocket,
    *,
    manifest: str = "",
    timeout_s: float = 120.0,
) -> bool:
    """Run the direct-API edit path.

    Returns:
        True  — all edits applied cleanly to disk.
        False — anything went wrong. Caller MUST fall back to SDK path.
                No partial edits are left on disk when we return False.
    """
    if not api_key:
        logger.info("execute_direct_edit: no API key — skipping direct path")
        return False
    if not relevant_files:
        logger.info("execute_direct_edit: no relevant files from Phase 4 — skipping")
        return False

    files, skipped = _load_files(workspace_path, relevant_files)
    if not files:
        logger.info("execute_direct_edit: all candidate files dropped (%s)", skipped[:3])
        return False

    try:
        await websocket.send_json({
            "type": "progress",
            "message": f"🎯 Applying surgical edit ({len(files)} file{'s' if len(files) != 1 else ''})...",
        })
    except Exception:
        pass

    # ── Build the prompt ─────────────────────────────────────────────
    # Keep the system prompt deliberately small — this is a one-shot edit,
    # not an agent. Every token here costs us on every request.
    system_prompt = (
        "You are a surgical code editor. You make the exact change requested "
        "and nothing else. Do not rewrite code, add comments, or refactor "
        "unrelated lines. Always match existing style, indentation, and "
        "quote convention. Every `old_string` in your response MUST appear "
        "verbatim in the target file — include enough surrounding lines to "
        "be unique. Prefer the smallest possible replacement."
    )

    files_block = "\n\n".join(
        f"===== FILE: {path} =====\n{content}" for path, content in files.items()
    )
    manifest_block = (
        f"\n\n===== TEMPLATE CONVENTIONS (for imports and component locations) =====\n"
        f"{manifest[:3500]}\n"
        if manifest.strip() else ""
    )
    plan_block = f"\n\n===== PLAN FROM ANALYSIS =====\n{plan.strip()}\n" if plan.strip() else ""

    user_prompt = (
        f"TASK: {task}\n"
        f"{plan_block}"
        f"{manifest_block}\n\n"
        f"===== FILES =====\n{files_block}\n\n"
        "Return the minimal set of edits to accomplish the task. "
        "Call the `apply_edits` tool exactly once."
    )

    headers = {
        "content-type": "application/json",
        "x-api-key": api_key,
        "anthropic-version": "2023-06-01",
    }
    payload = {
        "model": str(classification.get("model_id", "claude-sonnet-4-6")),
        "max_tokens": 8_000,
        "system": system_prompt,
        "tools": [_APPLY_EDITS_TOOL],
        "tool_choice": {"type": "tool", "name": "apply_edits"},
        "messages": [{"role": "user", "content": user_prompt}],
    }

    # ── Call Anthropic ───────────────────────────────────────────────
    try:
        async with httpx.AsyncClient(timeout=timeout_s) as client:
            resp = await client.post(_ANTHROPIC_URL, headers=headers, json=payload)
    except httpx.TimeoutException:
        logger.warning("execute_direct_edit: Anthropic timed out after %ss", timeout_s)
        return False
    except Exception as exc:
        logger.warning("execute_direct_edit: request error: %s", exc)
        return False

    if resp.status_code != 200:
        logger.warning(
            "execute_direct_edit: HTTP %d from Anthropic — falling back to SDK: %s",
            resp.status_code, resp.text[:300],
        )
        return False

    try:
        data = resp.json()
    except Exception as exc:
        logger.warning("execute_direct_edit: response not JSON: %s", exc)
        return False

    # Extract the tool_use block. We forced tool_choice so there should be
    # exactly one; reject anything else so a buggy model response never
    # silently succeeds.
    tool_input: Optional[dict] = None
    for block in data.get("content") or []:
        if isinstance(block, dict) and block.get("type") == "tool_use" and block.get("name") == "apply_edits":
            tool_input = block.get("input")
            break
    if not isinstance(tool_input, dict):
        logger.warning("execute_direct_edit: model did not call apply_edits (stop=%s)", data.get("stop_reason"))
        return False

    edits = tool_input.get("edits") or []
    if not isinstance(edits, list) or not edits:
        logger.warning("execute_direct_edit: empty edit list")
        return False

    # ── Validate every edit against the in-memory file contents BEFORE
    # writing anything. We must either apply all edits or none — a partial
    # apply would leave the workspace half-changed and the caller would
    # think it could safely retry via SDK.
    workspace_real = os.path.realpath(workspace_path)
    new_contents: dict[str, str] = {}
    for edit in edits:
        if not isinstance(edit, dict):
            logger.warning("execute_direct_edit: non-dict edit entry")
            return False
        rel_path = (edit.get("path") or "").strip()
        old_string = edit.get("old_string")
        new_string = edit.get("new_string")
        if not rel_path or old_string is None or new_string is None:
            logger.warning("execute_direct_edit: missing field in edit %.60s", str(edit))
            return False
        abs_path = os.path.realpath(os.path.join(workspace_path, rel_path))
        if not (abs_path == workspace_real or abs_path.startswith(workspace_real + os.sep)):
            logger.warning("execute_direct_edit: path escape rejected: %s", rel_path)
            return False
        # Start from the most recent content — either our prior edit's
        # result or disk. This lets a response legitimately chain two
        # edits against the same file (rare but valid).
        current = new_contents.get(rel_path)
        if current is None:
            current = files.get(rel_path)
            if current is None:
                # Creating a new file — require empty old_string.
                if old_string != "":
                    logger.warning(
                        "execute_direct_edit: file not pre-read and old_string non-empty: %s",
                        rel_path,
                    )
                    return False
                current = ""
        updated, ok = _apply_edit(current, old_string, new_string)
        if not ok:
            logger.warning(
                "execute_direct_edit: old_string not uniquely found in %s (len=%d)",
                rel_path, len(old_string),
            )
            return False
        new_contents[rel_path] = updated

    # ── Write all files atomically ───────────────────────────────────
    # Use the same tmp-file-then-rename pattern project_writer uses so a
    # mid-batch crash can't leave a half-written file on disk.
    written: list[str] = []
    try:
        for rel_path, content in new_contents.items():
            abs_path = os.path.join(workspace_path, rel_path)
            parent = os.path.dirname(abs_path)
            os.makedirs(parent, exist_ok=True)
            tmp_path = abs_path + ".lucid.tmp"
            with open(tmp_path, "w", encoding="utf-8") as f:
                f.write(content)
            os.replace(tmp_path, abs_path)
            written.append(rel_path)
    except Exception as exc:
        logger.error("execute_direct_edit: write failed for %s: %s", rel_path, exc)
        # Best-effort cleanup of any .lucid.tmp files that may have
        # survived a partial loop.
        for rel in new_contents:
            try:
                _leftover = os.path.join(workspace_path, rel) + ".lucid.tmp"
                if os.path.exists(_leftover):
                    os.remove(_leftover)
            except OSError:
                pass
        return False

    # Emit file_write_events so the Code-tab pills appear, same as the
    # SDK path does via its streaming tool-use events.
    for rel in written:
        try:
            await websocket.send_json({
                "type": "file_write_event",
                "filename": rel,
                "action": "edit",
            })
        except Exception:
            break

    summary = (tool_input.get("summary") or "").strip()
    try:
        await websocket.send_json({
            "type": "progress",
            "message": f"✅ Applied {len(written)} edit{'s' if len(written) != 1 else ''} in one shot"
                      + (f" — {summary[:120]}" if summary else ""),
        })
    except Exception:
        pass

    usage = data.get("usage") or {}
    logger.info(
        "execute_direct_edit: applied %d edits across %d file(s) "
        "[input=%d output=%d tokens]",
        len(edits), len(written),
        usage.get("input_tokens", 0), usage.get("output_tokens", 0),
    )
    return True
