// ─────────────────────────────────────────────────────────
//  Lucid AI — K8s Ops Folder Generator
//  Creates config.json and values.yaml for Helm deployments.
//  Company standard: microservice_v2 chart, GitLab registry,
//  nginx ingress with CORS, node affinity for workload.
// ─────────────────────────────────────────────────────────

/**
 * Generate K8s ops folder files (config.json + values.yaml).
 *
 * @param {object} opts
 * @param {string} opts.projectSlug — e.g. "lodify_admin_frontend"
 * @param {string} opts.repoPath — full GitLab repo path, e.g. "ucode/lodify/lodify_admin_frontend"
 * @param {string} opts.registryUrl — Docker registry (default: gitlab.udevs.io:5050)
 * @param {string} opts.domain — ingress domain, e.g. "app.lodify.io"
 * @param {string} opts.namespace — K8s namespace, e.g. "frontend-prod"
 * @param {number} opts.servicePort — from Dockerfile EXPOSE (default 80)
 * @param {string} opts.appLabel — label for K8s resources (default: derived from slug)
 * @returns {{ folderName: string, files: { path: string, content: string }[] }}
 */
export function generateOpsFolder({
  projectSlug,
  repoPath,
  registryUrl = 'gitlab.udevs.io:5050',
  domain = '*.udevs.io',
  namespace = 'frontend-prod',
  servicePort = 80,
  appLabel,
}) {
  const label = appLabel || projectSlug.replace(/_/g, '-');
  const imageRepo = `${registryUrl}/${repoPath || projectSlug}`;
  const tlsSecret = `${label}-tls`;

  const configJson = JSON.stringify(
    {
      repo_url:
        'https://gitlab.udevs.io/api/v4/projects/476/packages/helm/stable',
      chart: 'microservice_v2',
      version: '0.6.2',
    },
    null,
    4
  );

  const valuesYaml = `# ─────────────────────────────────────────────────
#  ${projectSlug} — Helm Values
#  Auto-generated by Lucid AI
# ─────────────────────────────────────────────────
global:
  replicaCount: 1
  environment: {}

replicaCount: 1

image:
  registry: ${registryUrl}/
  repository: ${repoPath || projectSlug}
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: "gitlab-registry"

nameOverride: ""
fullnameOverride: ""

labels:
  app: ${label}

serviceAccount:
  create: true
  annotations: {}
  name: "vault-auth"

podLabels:
  app: ${label}

podSecurityContext: {}
securityContext: {}

vault:
  enabled: false
  secretName: vault-secrets
  variables:
    VAULT_TOKEN: vault_token
    SECRETS_PATH:

environment: {}

volumes:
  enabled: false
  pvc:
    enabled: false
    existing_claim:
    name: pvc
    mountPath: /pv
    size: 1G
    class:
    accessModes:
      - ReadWriteOnce

service:
  type: ClusterIP
  annotations: {}
  specs:
    - port: ${servicePort}
      targetPort: ${servicePort}
      name: https

ingress:
  enabled: true
  rules:
    - annotations:
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "*"
        nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
      type: web
      hosts:
        - host: "${domain}"
          path: /
          servicePort: ${servicePort}
      tls:
        - secretName: ${tlsSecret}
          hosts:
            - "${domain}"

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: workload
              operator: In
              values:
                - "ucode-frontend"
`;

  return {
    folderName: projectSlug,
    files: [
      {
        path: `${projectSlug}/config.json`,
        content: configJson,
      },
      {
        path: `${projectSlug}/values.yaml`,
        content: valuesYaml,
      },
    ],
  };
}
